export const actionTypes = {
  CL_FETCH_TEAMS: "CL_FETCH_TEAMS",
  CL_CREATE_TEAM: "CL_CREATE_TEAM",
  CL_UPDATE_TEAM: "CL_UPDATE_TEAM",
  CL_DELETE_TEAM: "CL_DELETE_TEAM",
  CL_FETCH_GAMES: "CL_FETCH_GAMES",
  CL_CREATE_GAME: "CL_CREATE_GAME",
  CL_UPDATE_GAME: "CL_UPDATE_GAME",
  CL_DELETE_GAME: "CL_DELETE_GAME",
  CL_FETCH_BOARD: "CL_FETCH_BOARD",
  CL_UPDATE_BOARD: "CL_UPDATE_BOARD",
  CL_RESET_COUNTER: "CL_RESET_COUNTER",
}
